[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
coinflip = "2Y3e93kkP8RpNT2Jb5fKLVGqZKV8UDUcH4KM6TjDDJc4"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
